# Permalink
permalink: /posts/:title/

name: ridwanmsharif.github.io
url: https://ridwanmsharif.github.io

author:
  name: Ridwan Sharif
  email: ridwanmsharif@hotmail.com

sass:
  sass_dir: _scss
  style: compressed

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-feed

exclude:
  - script
  - Gemfile
  - Gemfile.lock
  - vendor
